name: Bundler
on: 
    workflow_dispatch:
jobs:
    build-macos: 
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node Environment
              uses: ./.github/actions/setup-node

            - name: Build
              shell: bash
              run: |
                pnpm install
                pnpm build

            - name: Upload
              run: |
                git config user.name github-actions[bot]
                git config user.email github-actions[bot]@users.noreply.github.com
                git add .
                git commit -m "chore: bundle"
                git tag ${{ env.TAG_NAME }}
                git push && git push --tags